- name: Creates jmeter folder
  become: yes
  file:
    path: "{{ ansible_env.HOME }}/jmeter"
    state: directory

- name: create test.jmx file
  template:
    src: "test.j2"
    dest: "{{ ansible_env.HOME }}/jmeter/test.jmx"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: jmeter test
  shell: "jmeter -nt {{ ansible_env.HOME }}/jmeter/test.jmx -g result.jtl"

- name: remove and create result folder
  become: yes
  file:
    path: "{{ ansible_env.HOME }}/jmeter/result"
    state: directory
  with_items:
    - absent
    - directory

- name: jmeter test
  shell: "jmeter -g result.jtl -o result"