- name: change permissive status to Selinux
  when: ansible_os_family == 'RedHat'
  become: yes
  selinux:
    policy: targeted
    state: permissive

- name: Install apache, java-1.8.0-openjdk (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  become: yes
  yum:
    name:
      - httpd
      - gnuplot
      - java-1.8.0-openjdk-devel.x86_64
    state: present

- name: Configure Bashrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64"


- name: Creates jmeter folder
  become: yes
  file:
    path: "{{ ansible_env.HOME }}/jmeter"
    state: directory

- name: Download jmeter
  become: yes
  get_url:
    url: https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.2.1.tgz
    dest: "{{ ansible_env.HOME }}/jmeter"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

# - name: Unarchive apache-jmeter-5.2.1.tgz
#   unarchive:
#     src: "{{ ansible_env.HOME }}/jmeter/apache-jmeter-5.2.1.tgz"
#     dest: "{{ ansible_env.HOME }}/jmeter/"
#     owner: "{{ ansible_env.USER }}"
#     group: "{{ ansible_env.USER }}"
#     mode: 0775

- name: Unarchive apache-jmeter-5.2.1.tgz
  shell: "tar -xvf {{ ansible_env.HOME }}/jmeter/apache-jmeter-5.2.1.tgz -C {{ ansible_env.HOME }}/jmeter"

- name: Configure Bashrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export JMETER_HOME={{ ansible_env.HOME }}/jmeter/apache-jmeter-5.2.1"
    - "export PATH=$JMETER_HOME/bin:$PATH"

- name: Add /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "192.168.0.67 test67 test67.dragonz.dev"
    - "192.168.0.68 test68 test68.dragonz.dev"
    - "192.168.0.69 test69 test69.dragonz.dev"
    - "192.168.0.70 test70 test70.dragonz.dev"